### ISSUE TITLE
Particles disappear

### ISSUE THREAD

**Issue by aaronjauf** [sfetzel/Labrador#1]
Hey, great project :)
I found a small bug.

Reproduction steps:
- add a fixed particle (P1)
- add a particle (P2)
- add a particle (P3)
- add a spring between (P1 and P2) (Spring 1)
- add a spring between (P2 and P3)
- press start => P2 and P3 fall straight down (Spring 1 seems to be deleted?)

"back to zero" makes the particles reappear in a strange position (sometimes they remain disappeared)

Greetings
Aaron

**Comment by sfetzel** [comment]
Please retest. Problem with model design: one law is supposed to create one force in current model. That does not fit with the real world, as this examples shows: two forces on P2 are created by Hook's Law. Should be changed. Unit test created in ParticleTest.ts

**Comment by aaronjauf** [comment]
nice :D working great
